[package]
name = "tokio-learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.37.0",features = ["full"] }
#获取cpu核心数库
num_cpus = "1.13.0"
crc32fast = "1.2.1"
